Squisher: Use our color conf

diff --git a/tools/opticharger b/tools/opticharger
--- a/tools/opticharger
+++ b/tools/opticharger
@@ -36,14 +36,14 @@ then
     APKCERTS=$OUT/obj/PACKAGING/target_files_intermediates/$TARGET_PRODUCT-target_files-$TARGET_BUILD_VARIANT.$USER/META/apkcerts.txt
     if [ ! -f "$APKCERTS" ];
     then
-        echo -e ${CL_RED}"Set APKCERTS to the path to your apkcerts.txt file"${CL_RST}
+        echo -e ${red}"Set APKCERTS to the path to your apkcerts.txt file"${txtrst}
         exit 1;
     fi
 fi
 
 if [ ! -f "$APKCERTS" ];
 then
-    echo -e ${CL_RED}"Invalid path to apkcerts.txt, set APKCERTS to the correct path."${CL_RST}
+    echo -e ${red}"Invalid path to apkcerts.txt, set APKCERTS to the correct path."${txtrst}
 fi
 
 if [ "$(which pngquant)" != "" ];
@@ -73,26 +73,26 @@ then
         pngout $1
     }
 else
-    echo -e ${CL_RED}"Please install pngquant, pngcrush, optipng, or pngout"${CL_RST}
+    echo -e ${red}"Please install pngquant, pngcrush, optipng, or pngout"${txtrst}
     exit 1;
 fi
 
 if [ "`which aapt`" = "" ];
 then
-    echo -e ${CL_RED}"Please ensure aapt is in your \$PATH"${CL_RST}
+    echo -e ${red}"Please ensure aapt is in your \$PATH"${txtrst}
     exit 1;
 fi
 
 if [ "`which zipalign`" = "" ];
 then
-    echo -e ${CL_RED}"Please ensure zipalign is in your \$PATH"${CL_RST}
+    echo -e ${red}"Please ensure zipalign is in your \$PATH"${txtrst}
     exit 1;
 fi
 
 if [ -e "$1" ];
 then
     NAME=`basename $1`;
-    echo -e ${CL_GRN}"Optimizing:${CL_RST} $NAME...";
+    echo -e ${grn}"Optimizing:${txtrst} $NAME...";
 
     if [ "$2" != "" ];
     then
@@ -105,7 +105,7 @@ then
         KEY="$CERT_PATH"/$2.pk8
         if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
         then
-            echo -e ${CL_RED}"$CERT does not exist!"${CL_RST};
+            echo -e ${red}"$CERT does not exist!"${txtrst};
             exit 1;
         fi
     else
@@ -113,24 +113,24 @@ then
         [ $QUIET ] || echo -e "APKINFO: $APKINFO";
         if [ "$APKINFO" = "" ];
         then
-            echo -e ${CL_RED}"No apk info for $NAME"${CL_RST};
+            echo -e ${red}"No apk info for $NAME"${txtrst};
             exit 1;
         fi
         CERT=`echo -e $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
         KEY=`echo -e $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
         if [ "$CERT" = "" ];
         then
-            echo -e ${CL_RED}"Unable to find certificate for $NAME"${CL_RST}
+            echo -e ${red}"Unable to find certificate for $NAME"${txtrst}
             exit 1;
         fi
         if [ "$CERT" = "PRESIGNED" ];
         then
-            echo -e ${CL_CYN}"$NAME is presigned, skipping"${CL_RST}
+            echo -e ${cya}"$NAME is presigned, skipping"${txtrst}
             exit 1;
         fi
     fi
 
-    [ $QUIET ] || echo -e ${CL_YLW}"Certificate:${CL_RST} $CERT";
+    [ $QUIET ] || echo -e ${ylw}"Certificate:${txtrst} $CERT";
 
     [ -d $TMPDIR/$NAME ] && rm -rf $TMPDIR/$NAME
     mkdir -p $TMPDIR/$NAME
@@ -139,19 +139,19 @@ then
     unzip -q $BASE/$1
     for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
     do
-        [ $QUIET ] || echo -e ${CL_GRN}"Crushing${CL_RST} $x"
+        [ $QUIET ] || echo -e ${grn}"Crushing${txtrst} $x"
         optimize_png $x
     done
     cp $BASE/$1 $BASE/$1.old
 
-    [ $QUIET ] || echo -e ${CL_GRN}"Repacking apk.."${CL_RST}
+    [ $QUIET ] || echo -e ${grn}"Repacking apk.."${txtrst}
     aapt p -0 .dat -0 .dict -0 .arsc -F $NAME .
 
-    [ $QUIET ] || echo -e ${CL_GRN}"Resigning with cert:${CL_RST} `echo -e $CERT`"
+    [ $QUIET ] || echo -e ${grn}"Resigning with cert:${txtrst} `echo -e $CERT`"
 
     [ $QUIET ] || echo java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
     java -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
-    [ $QUIET ] || echo -e ${CL_GRN}"Zipalign.."${CL_RST}
+    [ $QUIET ] || echo -e ${grn}"Zipalign.."${txtrst}
     zipalign -f 4 signed_$NAME $BASE/$1
     if [ ! $QUIET ]; then
         ls -l $BASE/$1.old
